#+TITLE: Emacs Configuration

This is the main configuration file for Emacs. It is called in
init.el. The file is written in org-mode, and parsed to elisp upon
loading, thanks to org-babel.

This file contains only the most general configurations, namely in the
first section. The second section pulls various packages from the
repository and installs them (only on the first run). More specific
configurations are delegated to individual configuration files. These
are called in the subsequent sections.

NOTE: Automatically installing "use-package" does not seem to work The
corresponding section is therefore deactivated. Instead, you need to
install "use package" manually for this configuration to work.

The configuration is a strongly based on a "manual fork" from
[[https://github.com/kjhealy/emacs-starter-kit][Kieran Healy's starter kit for the social sciences]].

* General configuration

These packages should be loaded on startup rather than auto-loaded,
because I need them always.

#+BEGIN_SRC emacs-lisp
  (require 'cl-lib) ; common lisp compatibility
  (require 'saveplace) ; put cursor where it was last when visiting file
  (require 'ffap) ; replaces certain key bindings for finding files with
		  ; commands that provide more sensible defaults.
  (require 'uniquify) ; make buffer names unique
  (require 'ansi-color) ; translate ANSI SGR escape sequences for Emacs 
  (require 'recentf) ; find files from a list of recently opened files
#+END_SRC

Set up several emacs package repositories.

#+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (setq package-archives '(("melpa"     . "https://melpa.org/packages/")
			   ("org"       . "https://orgmode.org/elpa/")
			   ("gnu"       . "https://elpa.gnu.org/packages/")
			   ("marmalade" . "https://marmalade-repo.org/packages/")))
  (package-initialize)
#+END_SRC

Don't clutter everything with backup files.

#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
#+END_SRC

* Custom functions
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/functions.org")
#+END_SRC
* Install stuff

Install a number of default packages on first run.

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/install-stuff.org")
#+END_SRC


Install use-package, so we can load packages on demand rather than on
startup.

This is deactivated. It doesn't seem to work. Instead, you need to
install "use package" manually for this configuration to work.

#+BEGIN_SRC emacs-lisp :tangle no
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
#+END_SRC

* Key-bindings and Usability
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/key-bindings.org")
#+END_SRC

* Theming and Usability
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/theming.org")
#+END_SRC

* Mode configurations
These are configurations for various modes.
** Text modes
#+BEGIN_SRC emacs-lisp
  (org-babel-load-file "~/.emacs.d/text.org")
#+END_SRC

** Org-mode
#+BEGIN_SRC emacs-lisp
  (org-babel-load-file "~/.emacs.d/org-mode.org")
#+END_SRC

** Python
#+BEGIN_SRC emacs-lisp :tangle no
  (org-babel-load-file "~/.emacs.d/python.org")
#+END_SRC

** Eshell
#+BEGIN_SRC emacs-lisp
  (org-babel-load-file "~/.emacs.d/eshell.org")
#+END_SRC

** Auto-completion
Autocompletion with yas snippets and company-mode.

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/auto-completion.org")
#+END_SRC

** LaTeX
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/latex.org")
#+END_SRC
** Lisp
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/lisp.org")
#+END_SRC
** Statistics
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/statistics.org")
#+END_SRC
** Miscellaneous
#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/mode-config.org")
#+END_SRC

* Spell-checking

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/flyspell.org")
#+END_SRC

* Local settings
Stuff that shouldn't be synchronized across computers goes here.

#+BEGIN_SRC emacs-lisp
(org-babel-load-file "~/.emacs.d/local.org")
#+END_SRC

* Finally: load settings from M-x customize
Not sure if necessary. Disabled.

#+BEGIN_SRC emacs-lisp :tangle no
  (load custom-file 'noerror)
#+END_SRC

* TODO Stuff that needs to be improved
+ [ ] Dired: Does moving to trash work?
+ [ ] I'm not sure if cl-lib actually works
+ [X] MELPA hangs -- needed https
+ [X] Key Bindings
+ [X] Usability and Theming
+ [X] Auto-completion
+ [X] Org-Mode
+ [X] Eshell
+ [ ] LaTeX
+ [X] Text
+ [ ] ESS
+ [X] Custom Functions
+ [X] Ubiquitous Packages
+ [X] Aspell
+ [X] Load snippets
+ [ ] Check out how load-package works and adapt config files.
