
#+TITLE: Mode Configurations

This file contains configurations for different modes.

* Dired config
** Dired extensions
#+begin_src emacs-lisp
  (load "dired-x")
  (require 'dired-quick-sort)
  (dired-quick-sort-setup)
#+end_src

** Visit all marked files using F
Bound to the "F" key.
#+begin_src emacs-lisp
  (eval-after-load "dired"
  '(progn
     (define-key dired-mode-map "F" 'my-dired-find-file)
     (defun my-dired-find-file (&optional arg)
       "Open each of the marked files, or the file under the point, or when prefix arg, the next N files "
       (interactive "P")
       (let* ((fn-list (dired-get-marked-files nil arg)))
         (mapc 'find-file fn-list)))))
#+end_src

** Stripe dired buffers (partly disabled)

Creates a stripe pattern as background for dired buffers (and other
tables, as defined below). Automatic dired hook disabled, because it
looks ugly in the sidebar and with icons.

#+begin_src emacs-lisp
(require 'stripe-buffer)
(add-hook 'org-mode-hook 'org-table-stripes-enable)
; (add-hook 'dired-mode-hook 'stripe-listify-buffer)  
#+end_src

** Reuse buffers (requires dired-single)
#+begin_src emacs-lisp
(defun my-dired-init ()
  "Bunch of stuff to run for dired, either immediately or when it's
   loaded."
  ;; <add other stuff here>
  (define-key dired-mode-map [return] 'dired-single-buffer)
  (define-key dired-mode-map [mouse-1] 'dired-single-buffer-mouse)
  (define-key dired-mode-map "^" 'dired-single-up-directory))

;; if dired's already loaded, then the keymap will be bound
(if (boundp 'dired-mode-map)
        ;; we're good to go; just add our bindings
        (my-dired-init)
  ;; it's not loaded yet, so add our bindings to the load-hook
  (add-hook 'dired-load-hook 'my-dired-init))
#+end_src

** Quickly copy/move between two frames
#+begin_src emacs-lisp
 (setq dired-dwim-target t)
#+end_src
** Omit dotfiles when omit-mode is active

Default toggle: C-x M-o
Unfortunately, this also hides the "..", which I find useful to go to
the parent directory. 

#+begin_src emacs-lisp
(setq dired-omit-files
                (concat dired-omit-files "\\|^\\..+$"))
#+end_src

** Refresh on file change

No need to constantly hit g.

#+begin_src emacs-lisp
(add-hook 'dired-mode-hook 'auto-revert-mode)
 #+end_src

** Truncate long lines rather than wrap them in dired
#+begin_src emacs-lisp
(add-hook 'dired-mode-hook 'toggle-truncate-lines)
#+end_src

* Pandoc config 
A pandoc menu for markdown and tex files. 

#+begin_src emacs-lisp 
  (load "pandoc-mode")
  (add-hook 'markdown-mode-hook 'pandoc-mode)
  (add-hook 'org-mode-hook 'pandoc-mode)
  (add-hook 'TeX-mode-hook 'pandoc-mode)
  (add-hook 'pandoc-mode-hook 'pandoc-load-default-settings)
  (global-set-key (kbd "C-c p") 'pandoc-main-hydra/body)
#+end_src

* Polymode config
Polymode is a package that supports multiple modes inside a single
buffer. It is aimed particularly at literate programming approaches
and supports, e.g., R and markdown in a single =.Rmd= file. So it is
very useful with knitr in R, given that ESS does not yet fully support
=.Rmd= files.

#+begin_src emacs-lisp
  (require 'poly-R)
  (require 'poly-markdown)
  ;;; polymode + markdown
  (add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
  ;;; polymode + R
  (add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
  (add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
  (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
#+end_src

* CSV config
Start CSV mode without text wrapping, with background lines, and with
auto-align enabled.

#+begin_src emacs-lisp 
  (add-hook 'csv-mode-hook 'csv-align-mode)
  (add-hook 'csv-mode-hook (lambda () (visual-line-mode -1)))
  (add-hook 'csv-mode-hook 'stripe-buffer-mode)
#+end_src

* Google Translate workaround
See this issue:
https://github.com/atykhonov/google-translate/issues/138

#+begin_src emacs-lisp 
 (defun google-translate--search-tkk () "Search TKK." (list 430675 2721866130))
 (setq google-translate-backend-method 'curl)
#+end_src
* elfeed subscriptions
#+begin_src emacs-lisp
(setq elfeed-feeds
      '("https://www.ipsa.org/latest-news-2/rss.xml"
        "https://www.ipsa.org/call-for-papers/rss.xml"
        "http://rc03.ipsa.org/feed/rss2"
        "https://verfassungsblog.de/feed/"
        "http://www.jepp-online.com/feed/"
        "https://www.regioparl.com/rss"
        "https://netzpolitik.org/feed"
        "http://doingbayesiandataanalysis.blogspot.com/feeds/posts/default"
        "https://www.cogitatiopress.com/politicsandgovernance/gateway/plugin/WebFeedGatewayPlugin/atom"
        "https://ejpr.onlinelibrary.wiley.com/feed/14756765/most-recent"
        "https://ejpr.onlinelibrary.wiley.com/feed/20478852/most-recent"
        "https://www.tandfonline.com/feed/rss/fwep20"
        "https://www.tandfonline.com/feed/rss/geui20"
        "https://www.tandfonline.com/feed/rss/rjpp20" "https://www.tandfonline.com/feed/rss/rpep21" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=ejta&type=axatoc&feed=rss" "https://onlinelibrary.wiley.com/action/showFeed?jc=14685965&type=etoc&feed=rss" "https://www.cambridge.org/core/rss/product/id/36840434E1E3E412FFAA6832AA9488AA" "https://onlinelibrary.wiley.com/feed/14679299/most-recent" "https://onlinelibrary.wiley.com/feed/28330188/most-recent" "https://kill-the-newsletter.com/feeds/ooi6dtjona47h3p5.xml" "https://onlinelibrary.wiley.com/action/showFeed?jc=15405907&type=etoc&feed=rss" "https://www.cambridge.org/core/rss/product/id/833A7242AC7B607BA7F6168DA072DB3B" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=cpsa&type=axatoc&feed=rss" "http://onlinelibrary.wiley.com/rss/journal/10.1002/(ISSN)1756-9338" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=ept&type=etoc&feed=rss" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=eupa&type=etoc&feed=rss" "http://rss.sciencedirect.com/publication/science/03069192" "https://onlinelibrary.wiley.com/action/showFeed?jc=14680491&type=etoc&feed=rss" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=ire&type=etoc&feed=rss" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=isq&type=etoc&feed=rss" "https://www.tandfonline.com/feed/rss/fcpa20" "http://api.ingentaconnect.com/content/lwish/sou/latest?format=rss" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=mila&type=etoc&feed=rss" "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1571-9979" "http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1088-4963" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=prqb&type=etoc&feed=rss" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=ptxa&type=etoc&feed=rss" "https://www.journals.uchicago.edu/action/showFeed?type=etoc&feed=rss&jc=jop" "https://onlinelibrary.wiley.com/feed/17401461/most-recent" "https://kill-the-newsletter.com/feeds/vqh5t91qqb7oty2p.xml" "https://www.cambridge.org/core/rss/product/id/146C8B1E6606CE283EBC5B10B255F4C0" "https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=ipsa&type=axatoc&feed=rss" "https://us12.campaign-archive.com/feed?u=149499106c3f4d0d4f6cf75c5&id=8f318ca8da"))
#+end_src
